[package]
name = "quantum-maze-challenge"
version = "1.0.0"
description = "Quantum physics-enhanced retro maze game - AWS Build Games Challenge"
license = "MIT"
repository = "https://github.com/RandomProjects-db/quantum-maze-challenge"
