name: Deploy Quantum Maze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pygame
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test game imports
      run: |
        python -c "import pygame; print('✅ Pygame available')"
        python -c "import config; print('✅ Configuration valid')"
    
    - name: Validate game structure
      run: |
        python -c "
import os
required_files = ['quantum_maze.py', 'config.py', 'README.md']
for file in required_files:
    if os.path.exists(file):
        print(f'✅ {file} found')
    else:
        print(f'❌ {file} missing')
        exit(1)
print('✅ All required files present')
"

  deploy-pages:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install system dependencies for web deployment
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pygame
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate web deployment files
      run: |
        python web_deploy.py
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web_output
        publish_branch: gh-pages
